### ISSUE TITLE
Problem with mermaid diagrams in dark themes

### ISSUE THREAD

**Issue by kaaljabr** [imageslr/typora-theme-bear#1]
Hi,

I love the compilation of all the cool themes. Is there a way to go around the mermaid diagrams in darks themes. Font is in black and it's almost invisible.

**Comment by imageslr** [comment]
@kaaljabr hi can you please paste your markdown content for the diagram ？ This is indeed a problem.

**Comment by imageslr** [comment]
Hi @kaaljabr  I have fixed this problem by adding variable `--mermaid-theme: dark`. This will use typora's default dark mermaid theme. Please try it out. If there is any unfixed theme, please let me know.
