### ISSUE TITLE
typing cursor not visible in dark themes when editing code blocks

### ISSUE THREAD

**Issue by bbhenry** [imageslr/typora-theme-bear#2]
Thank you for putting out beautiful themes inspired by Bear. I noticed that when I need to edit code blocks in dark themes, the typing cursor is too dark to be visible for editing. For example in this Dracula theme below, you can't locate the typing cursor. This happens in other dark theme as well.

![2021-09-20 at 1 17 AM](https://user-images.githubusercontent.com/667944/133973572-8f3fd30d-e33f-445f-8f0a-aa6847bfe9e5.png)

**Comment by imageslr** [comment]
Hi, I've fixed this bug. Please download the latest release.

**Comment by bbhenry** [comment]
That was quick , thank you :)
