### ISSUE TITLE
Heading level 1 and level 2 not displayed

### ISSUE THREAD

**Issue by bbhenry** [imageslr/typora-theme-bear#3]
When you put cursor on headings, it should display the level like following. But if you put cursor on level 1 or level 2 headings, it doesn't work.

![2021-09-20 at 2 58 PM](https://user-images.githubusercontent.com/667944/134081518-e92d0d3c-89ea-45bf-8037-e957abb09ce1.png)

**Comment by imageslr** [comment]
Hi @bbhenry , I've tried typora's default theme and the issue remained. Maybe it's typora's setting.
